name: Generar EXE Plano Win7
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.10'
        architecture: 'x86'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install uploadserver pyinstaller==5.13.2

    - name: Compilar Modo Plano
      run: |
        # Corregido: --win-no-prefer-redirects y añadido --collect-all para forzar librerías
        pyinstaller --onedir --console --name "Servidor_Final" --win-no-prefer-redirects --collect-all uploadserver --clean lanzador.py

    - name: Subir Carpeta
      uses: actions/upload-artifact@v4
      with:
        name: Servidor_Plano_Win7
        path: dist/Servidor_Final/
