name: Generar EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4 # Actualizado a v4
    
    - name: Verificar archivos
      run: dir # Esto nos mostrará en el log si lanzador.py existe
      
    - name: Configurar Python
      uses: actions/setup-python@v5 # Actualizado a v5
      with:
        python-version: '3.8.10'
        architecture: 'x86'

    - name: Instalar y Compilar
      run: |
        python -m pip install --upgrade pip
        pip install uploadserver pyinstaller
        pyinstaller --onefile --console --name "Servidor_Win7" lanzador.py

    - name: Entregar
      uses: actions/upload-artifact@v4 # Actualizado a v4 (más estable)
      with:
        name: Resultado_EXE
        path: dist/Servidor_Win7.exe
