name: Generar EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
        architecture: 'x86'
    - name: Instalar y Compilar
      run: |
        pip install uploadserver pyinstaller
        pyinstaller --onefile --console --name "Servidor_Win7" lanzador.py
    - name: Entregar
      uses: actions/upload-artifact@v3
      with:
        name: Resultado_EXE
        path: dist/Servidor_Win7.exe
